import { ChainId } from '../enums'

// in seconds
export const AVERAGE_BLOCK_TIME: { [chainId in ChainId]: number } = {
  [ChainId.ETHEREUM]: 13.5,
  [ChainId.RINKEBY]: 15.2,
  [ChainId.RINKEBY_SANDBOX]: 15.2,
  [ChainId.AVALANCHE]: 2.1,
  [ChainId.FUJI]: 2.1,
  [ChainId.FUJI_SANDBOX]: 2.1,
  [ChainId.BSC]: 3.1,
  [ChainId.BSC_TESTNET]: 3.1,
  [ChainId.BSC_TESTNET_SANDBOX]: 3.1,
  [ChainId.POLYGON]: 2.5,
  [ChainId.MUMBAI]: 3.5,
  [ChainId.MUMBAI_SANDBOX]: 3.5,
  [ChainId.ARBITRUM]: 13.5,
  [ChainId.ARBITRUM_RINKEBY]: 15.2,
  [ChainId.ARBITRUM_RINKEBY_SANDBOX]: 15.2,
  [ChainId.OPTIMISM]: 2,
  [ChainId.OPTIMISM_KOVAN]: 1,
  [ChainId.OPTIMISM_KOVAN_SANDBOX]: 1,
  [ChainId.FANTOM]: 1,
  [ChainId.FANTOM_TESTNET]: 3.5,
  [ChainId.FANTOM_TESTNET_SANDBOX]: 3.5,
  [ChainId.SWIMMER]: 5,
  [ChainId.SWIMMER_TESTNET]: 5,
  [ChainId.SWIMMER_TESTNET_SANDBOX]: 5,
  [ChainId.HARMONY]: 2,
  [ChainId.HARMONY_TESTNET]: 2,
  [ChainId.HARMONY_TESTNET_SANDBOX]: 2,
  [ChainId.ARCANA_TESTNET]: 2,
  [ChainId.ARCANA_TESTNET_SANDBOX]: 2,
  [ChainId.DEXALOT_TESTNET]: 10,
  [ChainId.DEXALOT_TESTNET_SANDBOX]: 10,
  [ChainId.DFK_TESTNET]: 10,
  [ChainId.DFK_TESTNET_SANDBOX]: 10,
}
