import { ChainKey, ChainStage } from '../enums'

export const CHAIN_STAGE: { [chainKey in ChainKey]: ChainStage } = {
  [ChainKey.ETHEREUM]: ChainStage.MAINNET,
  [ChainKey.RINKEBY]: ChainStage.TESTNET,
  [ChainKey.RINKEBY_SANDBOX]: ChainStage.TESTNET_SANDBOX,
  [ChainKey.BSC]: ChainStage.MAINNET,
  [ChainKey.BSC_TESTNET]: ChainStage.TESTNET,
  [ChainKey.BSC_TESTNET_SANDBOX]: ChainStage.TESTNET_SANDBOX,
  [ChainKey.AVALANCHE]: ChainStage.MAINNET,
  [ChainKey.FUJI]: ChainStage.TESTNET,
  [ChainKey.FUJI_SANDBOX]: ChainStage.TESTNET_SANDBOX,
  [ChainKey.POLYGON]: ChainStage.MAINNET,
  [ChainKey.MUMBAI]: ChainStage.TESTNET,
  [ChainKey.MUMBAI_SANDBOX]: ChainStage.TESTNET_SANDBOX,
  [ChainKey.ARBITRUM]: ChainStage.MAINNET,
  [ChainKey.ARBITRUM_RINKEBY]: ChainStage.TESTNET,
  [ChainKey.ARBITRUM_RINKEBY_SANDBOX]: ChainStage.TESTNET_SANDBOX,
  [ChainKey.OPTIMISM]: ChainStage.MAINNET,
  [ChainKey.OPTIMISM_KOVAN]: ChainStage.TESTNET,
  [ChainKey.OPTIMISM_KOVAN_SANDBOX]: ChainStage.TESTNET_SANDBOX,
  [ChainKey.FANTOM]: ChainStage.MAINNET,
  [ChainKey.FANTOM_TESTNET]: ChainStage.TESTNET,
  [ChainKey.FANTOM_TESTNET_SANDBOX]: ChainStage.TESTNET_SANDBOX,
  [ChainKey.SWIMMER]: ChainStage.MAINNET,
  [ChainKey.SWIMMER_TESTNET]: ChainStage.TESTNET,
  [ChainKey.SWIMMER_TESTNET_SANDBOX]: ChainStage.TESTNET_SANDBOX,
  [ChainKey.DFK_TESTNET]: ChainStage.TESTNET,
  [ChainKey.DFK_TESTNET_SANDBOX]: ChainStage.TESTNET_SANDBOX,
  [ChainKey.HARMONY]: ChainStage.MAINNET,
  [ChainKey.HARMONY_TESTNET]: ChainStage.TESTNET,
  [ChainKey.HARMONY_TESTNET_SANDBOX]: ChainStage.TESTNET_SANDBOX,
  [ChainKey.ARCANA_TESTNET]: ChainStage.TESTNET,
  [ChainKey.ARCANA_TESTNET_SANDBOX]: ChainStage.TESTNET_SANDBOX,
  [ChainKey.DEXALOT_TESTNET]: ChainStage.TESTNET,
  [ChainKey.DEXALOT_TESTNET_SANDBOX]: ChainStage.TESTNET_SANDBOX,
}
