import { ChainId } from '../enums'

export const RPCS: { [chainId in ChainId]?: string[] } = {
    [ChainId.ETHEREUM]: ['https://ethereum.publicnode.com', 'https://rpc.ankr.com/eth', 'https://eth-mainnet.public.blastapi.io'],
    [ChainId.GOERLI]: [
        'https://rpc.ankr.com/eth_goerli',
        'https://eth-goerli.public.blastapi.io',
        'https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161',
    ],
    [ChainId.GOERLI_SANDBOX]: [
        'https://rpc.ankr.com/eth_goerli',
        'https://eth-goerli.public.blastapi.io',
        'https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161',
    ],
    [ChainId.BSC]: ['https://rpc.ankr.com/bsc', 'https://bsc-mainnet.public.blastapi.io', 'https://bsc-dataseed.binance.org'],
    [ChainId.BSC_TESTNET]: [
        'https://bsc-testnet.public.blastapi.io',
        'https://data-seed-prebsc-1-s1.binance.org:8545',
        'https://data-seed-prebsc-2-s1.binance.org:8545',
    ],
    [ChainId.BSC_TESTNET_SANDBOX]: [
        'https://bsc-testnet.public.blastapi.io',
        'https://data-seed-prebsc-1-s1.binance.org:8545',
        'https://data-seed-prebsc-2-s1.binance.org:8545',
    ],
    [ChainId.AVALANCHE]: ['https://api.avax.network/ext/bc/C/rpc', 'https://avalanche-evm.publicnode.com'],
    [ChainId.FUJI]: ['https://api.avax-test.network/ext/bc/C/rpc', 'https://rpc.ankr.com/avalanche_fuji'],
    [ChainId.FUJI_SANDBOX]: ['https://api.avax-test.network/ext/bc/C/rpc', 'https://rpc.ankr.com/avalanche_fuji'],
    [ChainId.POLYGON]: ['https://polygon-rpc.com', 'https://rpc.ankr.com/polygon', 'https://polygon-bor.publicnode.com'],
    [ChainId.MUMBAI]: ['https://rpc-mumbai.maticvigil.com', 'https://rpc.ankr.com/polygon_mumbai', 'https://polygon-testnet.public.blastapi.io'],
    [ChainId.MUMBAI_SANDBOX]: [
        'https://rpc-mumbai.maticvigil.com',
        'https://rpc.ankr.com/polygon_mumbai',
        'https://polygon-testnet.public.blastapi.io',
    ],
    [ChainId.ARBITRUM]: ['https://arb1.arbitrum.io/rpc', 'https://rpc.ankr.com/arbitrum'],
    [ChainId.ARBITRUM_GOERLI]: ['https://goerli-rollup.arbitrum.io/rpc'],
    [ChainId.OPTIMISM]: ['https://mainnet.optimism.io'],
    [ChainId.OPTIMISM_GOERLI]: ['https://goerli.optimism.io'],
    [ChainId.FANTOM]: ['https://rpcapi.fantom.network', 'https://fantom-mainnet.public.blastapi.io'],
    [ChainId.FANTOM_TESTNET]: ['https://rpc.testnet.fantom.network'],
    [ChainId.FANTOM_TESTNET_SANDBOX]: ['https://rpc.testnet.fantom.network'],
    [ChainId.SWIMMER]: [
        'https://avax-cra-rpc.gateway.pokt.network',
        'https://subnets.avax.network/swimmer/mainnet/rpc',
        'https://rpc.swimmer.network/ext/bc/2K33xS9AyP9oCDiHYKVrHe7F54h2La5D8erpTChaAhdzeSu2RX/rpc',
    ],
    [ChainId.SWIMMER_TESTNET]: ['https://subnets.avax.network/swimmer/testnet/rpc'],
    [ChainId.SWIMMER_TESTNET_SANDBOX]: ['https://subnets.avax.network/swimmer/testnet/rpc'],
    [ChainId.DFK]: ['https://subnets.avax.network/defi-kingdoms/dfk-chain/rpc'],
    [ChainId.DFK_TESTNET]: ['https://subnets.avax.network/defi-kingdoms/dfk-chain-testnet/rpc'],
    [ChainId.DFK_TESTNET_SANDBOX]: ['https://subnets.avax.network/defi-kingdoms/dfk-chain-testnet/rpc'],
    [ChainId.HARMONY]: ['https://api.harmony.one'],
    [ChainId.HARMONY_TESTNET]: ['https://api.s0.b.hmny.io'],
    [ChainId.HARMONY_TESTNET_SANDBOX]: ['https://api.s0.b.hmny.io'],
    [ChainId.HARMONY_1]: ['https://s1.api.harmony.one'],
    [ChainId.HARMONY_1_TESTNET]: ['https://api.s1.b.hmny.io'],
    [ChainId.ARCANA_TESTNET]: ['https://blockchain-dev.arcana.network/'],
    [ChainId.ARCANA_TESTNET_SANDBOX]: ['https://blockchain-dev.arcana.network/'],
    [ChainId.DEXALOT]: ['https://subnets.avax.network/dexalot/mainnet/rpc'],
    [ChainId.DEXALOT_TESTNET]: ['https://subnets.avax.network/dexalot/testnet/rpc'],
    [ChainId.DEXALOT_TESTNET_SANDBOX]: ['https://subnets.avax.network/dexalot/testnet/rpc'],
    [ChainId.CASTLECRUSH_TESTNET]: ['https://subnets.avax.network/castle-crush/testnet/rpc'],
    [ChainId.CASTLECRUSH_TESTNET_SANDBOX]: ['https://subnets.avax.network/castle-crush/testnet/rpc'],
    [ChainId.CELO]: ['https://forno.celo.org', 'https://rpc.ankr.com/celo'],
    [ChainId.CELO_TESTNET]: ['https://alfajores-forno.celo-testnet.org'],
    [ChainId.CELO_TESTNET_SANDBOX]: ['https://alfajores-forno.celo-testnet.org'],
    [ChainId.MOONBEAM]: ['https://rpc.api.moonbeam.network', 'https://rpc.ankr.com/moonbeam', 'https://moonbeam.public.blastapi.io'],
    [ChainId.MOONBEAM_TESTNET]: [
        'https://rpc.api.moonbase.moonbeam.network',
        'https://rpc.testnet.moonbeam.network',
        'https://moonbase-alpha.public.blastapi.io',
    ],
    [ChainId.MOONBEAM_TESTNET_SANDBOX]: [
        'https://rpc.api.moonbase.moonbeam.network',
        'https://rpc.testnet.moonbeam.network',
        'https://moonbase-alpha.public.blastapi.io',
    ],
    [ChainId.GNOSIS]: ['https://rpc.gnosischain.com', 'https://rpc.ankr.com/gnosis', 'https://gnosis-mainnet.public.blastapi.io'],
    [ChainId.GNOSIS_TESTNET]: ['https://rpc.chiadochain.net'],
    [ChainId.GNOSIS_TESTNET_SANDBOX]: ['https://rpc.chiadochain.net'],
    [ChainId.BOBA]: ['https://mainnet.boba.network', 'https://lightning-replica.boba.network'],
    [ChainId.PORTAL_TESTNET]: ['https://subnets.avax.network/portal-fantasy/testnet/rpc'],
    [ChainId.PORTAL_TESTNET_SANDBOX]: ['https://subnets.avax.network/portal-fantasy/testnet/rpc'],
    [ChainId.AURORA]: ['https://mainnet.aurora.dev'],
    [ChainId.AURORA_TESTNET]: ['https://testnet.aurora.dev'],
    [ChainId.AURORA_TESTNET_SANDBOX]: ['https://testnet.aurora.dev'],
    [ChainId.FUSE]: ['https://fuse-mainnet.chainstacklabs.com', 'https://rpc.fuse.io', 'https://fuse-rpc.gateway.pokt.network'],
    [ChainId.FUSE_TESTNET]: ['https://rpc.fusespark.io'],
    [ChainId.FUSE_TESTNET_SANDBOX]: ['https://rpc.fusespark.io'],
    [ChainId.ZKSYNC_TESTNET]: ['https://zksync2-testnet.zksync.dev'],
    [ChainId.DOS_TESTNET]: ['https://test.doschain.com/jsonrpc'],
    [ChainId.APTOS]: ['https://fullnode.devnet.aptoslabs.com/v1'],
    [ChainId.APTOS_TESTNET]: ['https://fullnode.testnet.aptoslabs.com/v1'],
    [ChainId.APTOS_TESTNET_SANDBOX]: ['https://fullnode.devnet.aptoslabs.com/v1'],
    [ChainId.KLAYTN]: [
        'https://public-node-api.klaytnapi.com/v1/cypress',
        'https://public-en-cypress.klaytn.net',
        'https://klaytn01.fandom.finance',
        'https://klaytn02.fandom.finance',
    ],
    [ChainId.KLAYTN_TESTNET]: [
        'https://public-node-api.klaytnapi.com/v1/baobab',
        'https://api.baobab.klaytn.net:8651',
        'https://baobab01.fautor.app',
    ],
    [ChainId.METIS]: ['https://andromeda.metis.io/?owner=1088'],
    [ChainId.METIS_TESTNET]: ['https://goerli.gateway.metisdevops.link'],
    [ChainId.COREDAO_TESTNET]: ['https://rpc.test.btcs.network'],
}
