import { ChainId } from '../enums'

export const WEBSOCKETS: { [chainId in ChainId]: string[] } = {
  [ChainId.ETHEREUM]: [],
  [ChainId.RINKEBY]: ['wss://rinkeby-light.eth.linkpool.io/ws'],
  [ChainId.RINKEBY_SANDBOX]: ['wss://rinkeby-light.eth.linkpool.io/ws'],
  [ChainId.BSC]: ['wss://bsc-ws-node.nariox.org:443'],
  [ChainId.BSC_TESTNET]: [],
  [ChainId.BSC_TESTNET_SANDBOX]: [],
  [ChainId.AVALANCHE]: [],
  [ChainId.FUJI]: [],
  [ChainId.FUJI_SANDBOX]: [],
  [ChainId.POLYGON]: [],
  [ChainId.MUMBAI]: [],
  [ChainId.MUMBAI_SANDBOX]: [],
  [ChainId.ARBITRUM]: ['wss://arb1.arbitrum.io/ws'],
  [ChainId.ARBITRUM_RINKEBY]: ['wss://rinkeby.arbitrum.io/ws'],
  [ChainId.ARBITRUM_RINKEBY_SANDBOX]: ['wss://rinkeby.arbitrum.io/ws'],
  [ChainId.OPTIMISM]: ['wss://ws-mainnet.optimism.io'],
  [ChainId.OPTIMISM_KOVAN]: ['wss://ws-kovan.optimism.io'],
  [ChainId.OPTIMISM_KOVAN_SANDBOX]: ['wss://ws-kovan.optimism.io'],
  [ChainId.FANTOM]: ['wss://wsapi.fantom.network/'],
  [ChainId.FANTOM_TESTNET]: [],
  [ChainId.FANTOM_TESTNET_SANDBOX]: [],
  [ChainId.SWIMMER]: ['wss://subnets.avax.network/swimmer/mainnet/ws'],
  [ChainId.SWIMMER_TESTNET]: ['wss://subnets.avax.network/swimmer/testnet/ws'],
  [ChainId.SWIMMER_TESTNET_SANDBOX]: ['wss://subnets.avax.network/swimmer/testnet/ws'],
  [ChainId.DFK_TESTNET]: ['wss://subnets.avax.network/defi-kingdoms/dfk-chain-testnet/ws'],
  [ChainId.DFK_TESTNET_SANDBOX]: ['wss://subnets.avax.network/defi-kingdoms/dfk-chain-testnet/ws'],
  [ChainId.HARMONY]: ['wss://ws.s0.t.hmny.io/'],
  [ChainId.HARMONY_TESTNET]: ['wss://ws.s0.pops.one/', 'wss://ws.s0.pga.hmny.io/'],
  [ChainId.HARMONY_TESTNET_SANDBOX]: ['wss://ws.s0.pops.one/', 'wss://ws.s0.pga.hmny.io/'],
  [ChainId.ARCANA_TESTNET]: ['ws://blockchain-dev.arcana.network/ws'],
  [ChainId.ARCANA_TESTNET_SANDBOX]: ['ws://blockchain-dev.arcana.network/ws'],
  [ChainId.DEXALOT_TESTNET]: ['wss://subnets.avax.network/dexalot/testnet/ws'],
  [ChainId.DEXALOT_TESTNET_SANDBOX]: ['wss://subnets.avax.network/dexalot/testnet/ws'],
}
